/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import volume.Volume;
import volvis.ImageExportable;
import volvis.RendererSettings;

/**
 *
 * @author Tim
 */
public class RendererSettingsPanel extends javax.swing.JPanel {
	private RendererSettings settings;
	private ImageExportable renderer;
	
	/**
	 * Creates new form RendererSettingsPanel
	 */
	public RendererSettingsPanel(RendererSettings settings, ImageExportable renderer) {
		this.settings = settings;
		this.renderer = renderer;
		
		initComponents();
		
		chkUseGradientOpacity.setSelected(this.settings.isUseGradient());
		slFmin.setValue(this.settings.getFmin());
		slFfirst_min.setValue(this.settings.getFirstMin());
		slFmax.setValue(this.settings.getFmax());
		slOmin.setValue((int)(this.settings.getOmin() * 100));
		slOmax.setValue((int)(this.settings.getOmax() * 100));
		slFactor.setValue((int)(this.settings.getFactor() * 100));
	}
	
	public void setVolume(Volume v){
		slFmin.setMinimum(v.getMinimum());
		slFmax.setMinimum(v.getMinimum());
		slFmin.setMaximum(v.getMaximum());
		slFmax.setMaximum(v.getMaximum());
	}
	
	public void exportResult(File f, boolean result){
		if(result){
			lblExportResult.setText("Image saved to " + f.getPath());
		}else{
			lblExportResult.setText("Failed to save image");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        pnlOpacity = new javax.swing.JPanel();
        lblFmin = new javax.swing.JLabel();
        slFmin = new javax.swing.JSlider();
        txtFmin = new javax.swing.JTextField();
        txtOmin = new javax.swing.JTextField();
        slOmin = new javax.swing.JSlider();
        lblOmin = new javax.swing.JLabel();
        lblFmax = new javax.swing.JLabel();
        lblOmax = new javax.swing.JLabel();
        slFmax = new javax.swing.JSlider();
        slOmax = new javax.swing.JSlider();
        txtFmax = new javax.swing.JTextField();
        txtOmax = new javax.swing.JTextField();
        lblUseGradientOpacity = new javax.swing.JLabel();
        chkUseGradientOpacity = new javax.swing.JCheckBox();
        lblFactor = new javax.swing.JLabel();
        slFactor = new javax.swing.JSlider();
        txtFactor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblExport = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblExportResult = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblFfirst_min = new javax.swing.JLabel();
        slFfirst_min = new javax.swing.JSlider();
        txtFfirst_min = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlOpacity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gradient opacity settings"));

        lblFmin.setText("Minimum value");

        slFmin.setMaximum(255);
        slFmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFminStateChanged(evt);
            }
        });

        txtFmin.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFmin, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFmin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtFmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFminActionPerformed(evt);
            }
        });

        txtOmin.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slOmin, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), txtOmin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        slOmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slOminStateChanged(evt);
            }
        });

        lblOmin.setText("Minimum opacity");

        lblFmax.setText("Maximum value");

        lblOmax.setText("Maximum opacity");

        slFmax.setMaximum(255);
        slFmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFmaxStateChanged(evt);
            }
        });

        slOmax.setToolTipText("");
        slOmax.setValue(1);
        slOmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slOmaxStateChanged(evt);
            }
        });

        txtFmax.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFmax, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFmax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtFmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFmaxActionPerformed(evt);
            }
        });

        txtOmax.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slOmax, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), txtOmax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblUseGradientOpacity.setText("Use gradient opacity");

        chkUseGradientOpacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkUseGradientOpacityStateChanged(evt);
            }
        });

        lblFactor.setText("Factor");

        slFactor.setMaximum(1000);
        slFactor.setToolTipText("");
        slFactor.setValue(100);
        slFactor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFactorStateChanged(evt);
            }
        });

        txtFactor.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFactor, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), txtFactor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpacityLayout = new javax.swing.GroupLayout(pnlOpacity);
        pnlOpacity.setLayout(pnlOpacityLayout);
        pnlOpacityLayout.setHorizontalGroup(
            pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpacityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                        .addComponent(lblOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUseGradientOpacity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUseGradientOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addComponent(slFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlOpacityLayout.createSequentialGroup()
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addComponent(lblFmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addComponent(lblFactor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addComponent(lblOmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                                .addComponent(slFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(slFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        pnlOpacityLayout.setVerticalGroup(
            pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpacityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkUseGradientOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUseGradientOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOpacityLayout.createSequentialGroup()
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(slFmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slOmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOpacityLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Export"));

        lblExport.setText("Export high quality to PNG");

        btnExport.setText("Save");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        lblExportResult.setEditable(false);
        lblExportResult.setColumns(20);
        lblExportResult.setLineWrap(true);
        lblExportResult.setRows(5);
        jScrollPane1.setViewportView(lblExportResult);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExport)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExport, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("First"));
        jPanel3.setToolTipText("First");

        lblFfirst_min.setText("First minimum value");

        slFfirst_min.setMaximum(255);
        slFfirst_min.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFfirst_minStateChanged(evt);
            }
        });

        txtFfirst_min.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFfirst_min, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFfirst_min, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFfirst_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slFfirst_min, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtFfirst_min, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slFfirst_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFfirst_min, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFfirst_min, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("First");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void slFfirst_minStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFfirst_minStateChanged
        this.settings.setFirstMin(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFfirst_minStateChanged

    private void slFactorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFactorStateChanged
        this.settings.setFactor(((javax.swing.JSlider) evt.getSource()).getValue()/100.0);
    }//GEN-LAST:event_slFactorStateChanged

    private void chkUseGradientOpacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkUseGradientOpacityStateChanged
        this.settings.setUseGradient(((javax.swing.JCheckBox) evt.getSource()).isSelected());
    }//GEN-LAST:event_chkUseGradientOpacityStateChanged

    private void slOmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slOmaxStateChanged
        this.settings.setOmax(((javax.swing.JSlider) evt.getSource()).getValue()/100.0);
    }//GEN-LAST:event_slOmaxStateChanged

    private void slFmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFmaxStateChanged
        this.settings.setFmax(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFmaxStateChanged

    private void slOminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slOminStateChanged
        this.settings.setOmin(((javax.swing.JSlider) evt.getSource()).getValue()/100.0);
    }//GEN-LAST:event_slOminStateChanged

    private void slFminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFminStateChanged
        this.settings.setFmin(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFminStateChanged

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Image", "png");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        int ret = chooser.showSaveDialog(null);
        if(ret == JFileChooser.APPROVE_OPTION){
            File selected = chooser.getSelectedFile();
			if(!selected.getAbsolutePath().endsWith(".png")){
				selected = new File(selected + ".png");
			}
            this.renderer.exportImage(selected);
            this.lblExportResult.setText("Exporting image...");
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtFmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFmaxActionPerformed

    private void txtFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactorActionPerformed

    private void txtFminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JCheckBox chkUseGradientOpacity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExport;
    private javax.swing.JTextArea lblExportResult;
    private javax.swing.JLabel lblFactor;
    private javax.swing.JLabel lblFfirst_min;
    private javax.swing.JLabel lblFmax;
    private javax.swing.JLabel lblFmin;
    private javax.swing.JLabel lblOmax;
    private javax.swing.JLabel lblOmin;
    private javax.swing.JLabel lblUseGradientOpacity;
    private javax.swing.JPanel pnlOpacity;
    private javax.swing.JSlider slFactor;
    private javax.swing.JSlider slFfirst_min;
    private javax.swing.JSlider slFmax;
    private javax.swing.JSlider slFmin;
    private javax.swing.JSlider slOmax;
    private javax.swing.JSlider slOmin;
    private javax.swing.JTextField txtFactor;
    private javax.swing.JTextField txtFfirst_min;
    private javax.swing.JTextField txtFmax;
    private javax.swing.JTextField txtFmin;
    private javax.swing.JTextField txtOmax;
    private javax.swing.JTextField txtOmin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
