/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import volume.Volume;
import volvis.RendererSettings;

/**
 *
 * @author Tim
 */
public class RendererSettingsPanel extends javax.swing.JPanel {
	private RendererSettings settings;
	
	/**
	 * Creates new form RendererSettingsPanel
	 */
	public RendererSettingsPanel(RendererSettings settings) {
		this.settings = settings;
		
		initComponents();
		
		chkUseGradientOpacity.setSelected(this.settings.isUseGradient());
		slFmin.setValue(this.settings.getFmin());
                slFmin1.setValue(this.settings.getFirstMin());
		slFmax.setValue(this.settings.getFmax());
		slOmin.setValue((int)(this.settings.getOmin() * 100));
		slOmax.setValue((int)(this.settings.getOmax() * 100));
	}
	
	public void setVolume(Volume v){
		slFmin.setMinimum(v.getMinimum());
		slFmax.setMinimum(v.getMinimum());
		slFmin.setMaximum(v.getMaximum());
		slFmax.setMaximum(v.getMaximum());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        pnlOpacity = new javax.swing.JPanel();
        lblFmin = new javax.swing.JLabel();
        slFmin = new javax.swing.JSlider();
        txtFmin = new javax.swing.JTextField();
        txtOmin = new javax.swing.JTextField();
        slOmin = new javax.swing.JSlider();
        lblOmin = new javax.swing.JLabel();
        lblFmax = new javax.swing.JLabel();
        lblOmax = new javax.swing.JLabel();
        slFmax = new javax.swing.JSlider();
        slOmax = new javax.swing.JSlider();
        txtFmax = new javax.swing.JTextField();
        txtOmax = new javax.swing.JTextField();
        lblUseGradientOpacity = new javax.swing.JLabel();
        chkUseGradientOpacity = new javax.swing.JCheckBox();
        txtFmin1 = new javax.swing.JTextField();
        slFmin1 = new javax.swing.JSlider();
        lblFmin1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlOpacity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gradient opacity settings"));

        lblFmin.setText("Minimum value");

        slFmin.setMaximum(255);
        slFmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFminStateChanged(evt);
            }
        });

        txtFmin.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFmin, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFmin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtFmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFminActionPerformed(evt);
            }
        });

        txtOmin.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slOmin, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), txtOmin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        slOmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slOminStateChanged(evt);
            }
        });

        lblOmin.setText("Minimum opacity");

        lblFmax.setText("Maximum value");

        lblOmax.setText("Maximum opacity");

        slFmax.setMaximum(255);
        slFmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFmaxStateChanged(evt);
            }
        });

        slOmax.setToolTipText("");
        slOmax.setValue(1);
        slOmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slOmaxStateChanged(evt);
            }
        });

        txtFmax.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFmax, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFmax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtOmax.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slOmax, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), txtOmax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblUseGradientOpacity.setText("Use gradient opacity");

        chkUseGradientOpacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkUseGradientOpacityStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlOpacityLayout = new javax.swing.GroupLayout(pnlOpacity);
        pnlOpacity.setLayout(pnlOpacityLayout);
        pnlOpacityLayout.setHorizontalGroup(
            pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpacityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                        .addComponent(lblOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(slOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOpacityLayout.createSequentialGroup()
                        .addComponent(lblFmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(slFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                        .addComponent(lblOmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(slOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUseGradientOpacity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(lblFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlOpacityLayout.createSequentialGroup()
                                .addComponent(slFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkUseGradientOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlOpacityLayout.setVerticalGroup(
            pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpacityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkUseGradientOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUseGradientOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slFmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFmax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOpacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slOmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOmax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFmin1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, slFmin1, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtFmin1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtFmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFmin1ActionPerformed(evt);
            }
        });

        slFmin1.setMaximum(255);
        slFmin1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slFmin1StateChanged(evt);
            }
        });

        lblFmin1.setText("Minimum value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFmin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(slFmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(pnlOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slFmin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void slFminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFminStateChanged
        this.settings.setFmin(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFminStateChanged

    private void slOminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slOminStateChanged
        this.settings.setOmin(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slOminStateChanged

    private void slFmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFmaxStateChanged
        this.settings.setFmax(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFmaxStateChanged

    private void slOmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slOmaxStateChanged
        this.settings.setOmax(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slOmaxStateChanged

    private void chkUseGradientOpacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkUseGradientOpacityStateChanged
        this.settings.setUseGradient(((javax.swing.JCheckBox) evt.getSource()).isSelected());
    }//GEN-LAST:event_chkUseGradientOpacityStateChanged

    private void slFmin1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slFmin1StateChanged
       this.settings.setFirstMin(((javax.swing.JSlider) evt.getSource()).getValue());
    }//GEN-LAST:event_slFmin1StateChanged

    private void txtFmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFmin1ActionPerformed

    private void txtFminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkUseGradientOpacity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFmax;
    private javax.swing.JLabel lblFmin;
    private javax.swing.JLabel lblFmin1;
    private javax.swing.JLabel lblOmax;
    private javax.swing.JLabel lblOmin;
    private javax.swing.JLabel lblUseGradientOpacity;
    private javax.swing.JPanel pnlOpacity;
    private javax.swing.JSlider slFmax;
    private javax.swing.JSlider slFmin;
    private javax.swing.JSlider slFmin1;
    private javax.swing.JSlider slOmax;
    private javax.swing.JSlider slOmin;
    private javax.swing.JTextField txtFmax;
    private javax.swing.JTextField txtFmin;
    private javax.swing.JTextField txtFmin1;
    private javax.swing.JTextField txtOmax;
    private javax.swing.JTextField txtOmin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
